image:
  thegaragebandofit/gitpod-workspace_one-kubernetes:gcloud-0.0.3
#  file: .gitpod.Dockerfile
tasks:
  - init: |
      echo 'TODO: build project'
      git clone https://github.com/one-kubernetes/dev1-aspicot-app.git
      git clone https://github.com/one-kubernetes/dev2-carapuce-app.git
      git clone https://github.com/one-kubernetes/dev2-helm-charts.git
    command: |
      echo 'TODO: start app'

workspaceLocation:
  "."